/*

Get_Schd_Prod_Extr_Tasks_Lst: 
    {
        "@odata.etag": "W/\"JzIwOzE3MTM2NTg3OTAzOTg1NjM5MTkxMTswMDsn\"",
        "SystemId": "b3ab7edf-5d8a-ee11-b81e-005056a913e0",
        "Machine_Center_No2": "10001",
        "Prod_Order_No": "105769",
        "Prod_Order_Line": 10000,
        "Operation_No": "10",
        "Next_Operation_No": "",
        "Previous_to_Suspend_No": "",
        "SFT_Status": " ",
        "Task_Status": "",
        "Fixed_Scrap_Quantity_FEET": 0,
        "Fixed_Scrap_Quantity": 650,
        "Scrap_Factor": 3,
        "Expected_Capacity_Need_Mins": 1332060,
        "Last_Modified_Date": "2023-07-24",
        "Last_Modified_Time": "12:49:27.097",
        "SFT_Display_Order": 419,
        "Markers": "",
        "Actual_Output_Qty_FEET": 0,
        "Actual_Dispose_Qty_FEET": 0,
        "Item_No": "PBF 200 T",
        "Output_Width": "60",
        "Prod_Target_Gauge": 194,
        "Trim": false,
        "Trial": false,
        "Treated": true,
        "Bubble_Width": 0,
        "No_of_Layers": "3",
        "Production_UOM": "LBS",
        "Quantity": 1,
        "V2UOM_Quantity": 21,
        "Gauge": 200,
        "Creation_Date": "2018-06-04",
        "Due_Date": "2019-06-04",
        "Authorization_No": "",
        "Expected_Due_Date": "2019-06-04",
        "Recipe_No": "404",
        "Re_Run": false,
        "Re_Run_Reason": "",
        "Code": "PBF",
        "Color": "White",
        "Treat_Target": "40",
        "Treat_Range": "-2/+2",
        "Recipe_Barrier": "No",
        "Recipe_Color": "Clear - Gloss"
    }


//////////////////////////////////////////////////
Get_Schd_Prod_InLok_Tasks_list
      {
            "@odata.etag": "W/\"JzIwOzE0MTE0MTI1NDA0OTAyNzQzODQ4MTswMDsn\"",
            "SystemId": "01c26b13-1fba-ee11-b88f-005056a9a7e6",
            "Type": "Machine Center",
            "Machine_Center_No2": "29001",
            "Work_Center_No": "INNO-LOK",
            "Combo_No": "",
            "Prod_Order_No": "167717",
            "Prod_Order_Line_No": 10000,
            "Operation_No": "40",
            "Next_Operation_No": "",
            "Previous_Operation_No": "30",
            "Previous_to_Suspend_No": "",
            "SFT_Status": "In Progress",
            "Task_Status": "",
            "Fixed_Scrap_Quantity_FEET": 1350,
            "Fixed_Scrap_Quantity": 2400,
            "Scrap_Factor": 3,
            "Input_Quantity_FEET": 88256.25,
            "Input_Quantity": 156900,
            "Output_Quantity": 150000,
            "Output_Quantity_FEET": 168750,
            "Actual_Output_Qty": 137285,
            "FEET_Actual_Qty": 154473,
            "V2UOM_Actual_Qty": 154473,
            "Expected_Capacity_Need_Mins": 73560000,
            "Routing_Steps": "PR10 LM2 SL2 IN1",
            "Lanes_Across": 2,
            "Next_Step_Work_Center_Code": "",
            "Last_Modified_Date": "2024-02-20",
            "Last_Modified_Time": "21:20:31.433",
            "SFT_Display_Order": 408,
            "Markers": "",
            "Input_Qty_Factor_FEET": 0.5625,
            "Actual_Dispose_Qty_FEET": 0,
            "Prod_Order_Line_No2": 10000,
            "Production_UOM": "IMP",
            "Remaining_Quantity": 12715,
            "V2UOM_Remaining_Qty": 0,
            "Quantity": 150000,
            "V2UOM_Quantity": 84375,
            "Trial": false,
            "Prod_Order_No_Ref_Link": "",
            "Prod_Ord_Line_No_Ref_Link": 0,
            "Press_Op_Ref_Link": false,
            "Lam_Op_Ref_Link": false,
            "Slit_Op_Ref_Link": false,
            "VFold_Op_Ref_Link": false,
            "Wickt_Op_Ref_Link": false,
            "Pouch_Op_Ref_Link": false,
            "Inno_Lok_Op_Ref_Link": 0,
            "Graphic_No": "69-116-R2",
            "GC": false,
            "FGS_Syncronized": true,
            "Film_Structure": "PET",
            "Treat": true,
            "Hot_Job": false,
            "COA": true,
            "Gauge": 48,
            "Web_Width": 47.75,
            "Long_Description": "DG 85764 BRD NGT BB INNO 22OZ",
            "Customer_PO_No": "161582",
            "Customer_Part_No": "339816",
            "Accredo_Part_No": "KSF01-ZF-03455",
            "Qty_Ordered": 125000,
            "Qty_Ordered_UOM": "IMP",
            "Pouch_Height": 0,
            "Pouch_Width": 0,
            "Pouch_Bottom_Gusset": 0,
            "Pouch_Wicket": false,
            "Pouch_Tear_Notch": false,
            "Pouch_Handle": false,
            "Pouch_Laser_Score": false,
            "Pouch_Zipper": "",
            "Slider": "",
            "Pouch_Zipper_Item_No": "",
            "Pouch_Bottom_Gusset_Seal": false,
            "Pouch_Bottom_Gusset_Width": "",
            "Pouch_Bot_Gusset_Width_Other": "",
            "Is_Inno_Lok_Zipper": true,
            "Inno_Lok_UOM": "in",
            "Inno_Lok_Zipper_Length": 6.875,
            "Inno_Lok_Loc_from_top_of_Imp": 2,
            "Inno_Lok_Loc_from_edge_of_Imp": 0,
            "Creation_Date": "2024-01-23",
            "Due_Date": "2024-03-07",
            "Last_Date_Modified": "2024-01-23",
            "Authorization_No": "1.23.24 KSF",
            "Expected_Due_Date": "2024-03-07",
            "Customer_Samples_Requested": false,
            "CSR_Quantity": 0,
            "CSR_UOM": " ",
            "CSR_Department": "",
            "Marketing_Samples_Requested": false,
            "MSR_Quantity": 0,
            "MSR_UOM": " ",
            "MSR_Department": "",
            "Re_Run": false,
            "Re_Run_Reason": "",
            "First_Time_Run_for_Item": false,
            "First_Time_Run_for_Graphic": false,
            "Hold": false,
            "Hold_Reason": "",
            "Cancelled": false,
            "Cancelling_Reason": ""
        },










Get_Schd_Prod_Lam_Tasks_List


    "value": [
        {
            "@odata.etag": "W/\"JzIwOzE3MzU0ODAzNTI2Mzg1MTA2Njg1MTswMDsn\"",
            "SystemId": "383e589d-658a-ee11-b81e-005056a913e0",
            "Type": "Machine Center",
            "Machine_Center_No2": "14002",
            "Work_Center_No": "LAMINATION",
            "Combo_No": "",
            "Prod_Order_No": "107197",
            "Prod_Order_Line_No": 10000,
            "Operation_No": "20",
            "Next_Operation_No": "",
            "Previous_Operation_No": "",
            "Previous_to_Suspend_No": "",
            "SFT_Status": " ",
            "Task_Status": "",
            "Fixed_Scrap_Quantity_FEET": 700,
            "Fixed_Scrap_Quantity": 700,
            "Scrap_Factor": 1,
            "Input_Quantity_FEET": 701.01,
            "Input_Quantity": 701.01,
            "Output_Quantity": 1,
            "Output_Quantity_FEET": 1,
            "Actual_Output_Qty": 0,
            "FEET_Actual_Qty": 0,
            "V2UOM_Actual_Qty": 0,
            "Expected_Capacity_Need_Mins": 5552946,
            "Routing_Steps": "LM2",
            "Lanes_Across": 1,
            "Next_Step_Work_Center_Code": "",
            "Routing_Link_Code": "LAM",
            "Barrier": " ",
            "Last_Modified_Date": "2024-01-15",
            "Last_Modified_Time": "14:59:12.9",
            "SFT_Display_Order": 776,
            "Markers": "",
            "Input_Qty_Factor_FEET": 1,
            "Actual_Dispose_Qty_FEET": 0,
            "Prod_Order_Line_No2": 10000,
            "Production_UOM": "FEET",
            "Remaining_Quantity": 1,
            "V2UOM_Remaining_Qty": 0,
            "Quantity": 1,
            "V2UOM_Quantity": 0,
            "Trial": false,
            "Prod_Order_No_Ref_Link": "",
            "Prod_Ord_Line_No_Ref_Link": 0,
            "Press_Op_Ref_Link": false,
            "Lam_Op_Ref_Link": false,
            "Slit_Op_Ref_Link": false,
            "VFold_Op_Ref_Link": false,
            "Wickt_Op_Ref_Link": false,
            "Pouch_Op_Ref_Link": false,
            "Graphic_No": "",
            "GC": false,
            "Treat": true,
            "Hot_Job": false,
            "COA": false,
            "Gauge": 200,
            "Web_Width": 1,
            "Long_Description": "LAMINATION BLACK LINE",
            "Customer_PO_No": "",
            "Customer_Part_No": "",
            "Accredo_Part_No": "ACC01-SAMPLE#10",
            "Lam_Top_Film_Type": "EX18-058",
            "Lam_Top_Gauge": 28,
            "Lam_Top_Width": 0,
            "Lam_Middle_Web_Film_Type": "EX18-058",
            "Lam_Middle_Web_Gauge": 28,
            "Lam_Middle_Web_Width": 0,
            "Lam_Back_Sheet_Film_Type": "ACC",
            "Lam_Back_Sheet_Gauge": 200,
            "Lam_Back_Sheet_Width": 1,
            "Lam_Wind_1": "n/a",
            "Lam_Wind_2": "n/a",
            "Lam_Sleeve": "",
            "Lam_Top_Item_No": "",
            "Lam_Middle_Web_Item_No": "",
            "Lam_Back_Sheet_Item_No": "ACC01-SAMPLE#10",
            "Lam_Top_Item_Width": "",
            "Lam_Middle_Web_Item_Width": "",
            "Lam_Back_Sheet_Item_Width": "",
            "Printed_Item_No": "ACC01-SAMPLE#10",
            "Printed_Item_Width": "",
            "Creation_Date": "2018-07-30",
            "Due_Date": "2018-07-30",
            "Last_Date_Modified": "2018-07-30",
            "Authorization_No": "FOR LAM-2",
            "Expected_Due_Date": "2018-07-30",
            "Customer_Samples_Requested": false,
            "CSR_Quantity": 0,
            "CSR_UOM": " ",
            "CSR_Department": "",
            "Marketing_Samples_Requested": false,
            "MSR_Quantity": 0,
            "MSR_UOM": " ",
            "MSR_Department": "",
            "Re_Run": false,
            "Re_Run_Reason": "",
            "First_Time_Run_for_Item": false,
            "First_Time_Run_for_Graphic": false,
            "Hold": false
        },



Get_Schd_Prod_Slit_Tasks_List
{
            "@odata.etag": "W/\"JzE5OzEwNzI4MjA1MTQ0Mjg0NzI1MDIxOzAwOyc=\"",
            "SystemId": "483e589d-658a-ee11-b81e-005056a913e0",
            "Type": "Machine Center",
            "Machine_Center_No2": "15001",
            "Work_Center_No": "SLITTING",
            "Combo_No": "",
            "Prod_Order_No": "111938",
            "Prod_Order_Line_No": 10000,
            "Operation_No": "30",
            "Next_Operation_No": "",
            "Previous_Operation_No": "",
            "Previous_to_Suspend_No": "",
            "SFT_Status": " ",
            "Task_Status": "PLANNING COMPLETED",
            "Fixed_Scrap_Quantity_FEET": 150,
            "Fixed_Scrap_Quantity": 150,
            "Scrap_Factor": 7,
            "Input_Quantity_FEET": 151.07,
            "Input_Quantity": 151.07,
            "Output_Quantity": 1,
            "Output_Quantity_FEET": 1,
            "Actual_Output_Qty": 0,
            "FEET_Actual_Qty": 0,
            "V2UOM_Actual_Qty": 0,
            "Expected_Capacity_Need_Mins": 1845324,
            "Routing_Steps": "SL1",
            "Lanes_Across": 1,
            "Next_Step_Work_Center_Code": "",
            "Last_Modified_Date": "2023-11-19",
            "Last_Modified_Time": "06:36:38.137",
            "SFT_Display_Order": 224,
            "Markers": "",
            "Input_Qty_Factor_FEET": 1,
            "Actual_Dispose_Qty_FEET": 0,
            "Prod_Order_Line_No2": 10000,
            "Production_UOM": "FEET",
            "Remaining_Quantity": 1,
            "V2UOM_Remaining_Qty": 0,
            "Quantity": 1,
            "V2UOM_Quantity": 0,
            "Trial": false,
            "Variant_Code": "",
            "Prod_Order_No_Ref_Link": "",
            "Prod_Ord_Line_No_Ref_Link": 0,
            "Press_Op_Ref_Link": false,
            "Lam_Op_Ref_Link": false,
            "Slit_Op_Ref_Link": false,
            "VFold_Op_Ref_Link": false,
            "Wickt_Op_Ref_Link": false,
            "Pouch_Op_Ref_Link": false,
            "Inno_Lok_Op_Ref_Link": 0,
            "Graphic_No": "",
            "GC": false,
            "Treat": true,
            "Hot_Job": false,
            "COA": false,
            "Gauge": 48,
            "Web_Width": 1,
            "Long_Description": "SLITTER REWORK SFTU LINE MARKER",
            "Customer_PO_No": "",
            "Customer_Part_No": "",
            "Accredo_Part_No": "ACC01-SAMPLE-53",
            "Slitting_Width": 1,
            "Slitting_AC": 1,
            "Slitting_Wind": "N/A",
            "Slitting_Dusting_Perc": 0,
            "Venting_Laser": false,
            "Printed_No_Across_FGS": 0,
            "Impression_per_Finished_Web": 0,
            "Film_Structure": "PET",
            "Web_Width_Tolerance": "",
            "Slitting_Min_Roll_Length": "",
            "Slitting_Max_Roll_Length": "",
            "Slitting_Trim_Width": 0,
            "Slitting_Next_Production_Step": " ",
            "Finish_at_Press_of_Splices": 0,
            "Creation_Date": "2019-01-02",
            "Due_Date": "2025-01-02",
            "Last_Date_Modified": "2019-01-02",
            "Authorization_No": "FOR SLITTER REWORK LINE",
            "Expected_Due_Date": "2025-01-02",
            "Customer_Samples_Requested": false,
            "CSR_Quantity": 0,
            "CSR_UOM": " ",
            "CSR_Department": "",
            "Marketing_Samples_Requested": false,
            "MSR_Quantity": 0,
            "MSR_UOM": " ",
            "MSR_Department": "",
            "Re_Run": false,
            "Re_Run_Reason": "",
            "First_Time_Run_for_Item": false,
            "First_Time_Run_for_Graphic": false,
            "Hold": false
        },

*/
